# Generated by Django 4.0.3 on 2023-12-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0005_alter_booking_seats_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('1', 'В процессе'), ('2', 'Оплачено')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('1', 'Активно'), ('2', 'Неактивна')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('1', 'Активно'), ('2', 'Неактивна')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('1', 'Активно'), ('2', 'Неактивна')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('1', 'Активно'), ('2', 'Отменено')], default=1, max_length=2),
        ),
    ]
