# Generated by Django 4.0.3 on 2023-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0006_alter_booking_status_alter_bus_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mail',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
